### ISSUE TITLE
Failed to access socket path

### ISSUE THREAD

**Issue by emteedubs** [crazy-max/docker-fail2ban#16]
Running the container on a Synology NAS.
Other containers sharing same docker-compose file include Traefik and other typical media server services. 

Getting this error when running the following command on the container:
``` 
"docker-compose run -T fail2ban fail2ban-client status" 
```

which results in the following error:
```
[1]: ERROR   Failed to access socket path: /var/run/fail2ban/fail2ban.sock. Is fail2ban running?
```

following excerpt from docker-compose.yml file:
```
  fail2ban:
    image: crazymax/fail2ban:latest
    container_name: fail2ban
    restart: "no"
    cap_add:
      - NET_ADMIN
      - NET_RAW
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
      - F2B_LOG_LEVEL=DEBUG
      - F2B_DB_PURGE_AGE=1d
      - F2B_MAX_RETRY=3
      - F2B_DEST_EMAIL=webmaster@example.com
      - F2B_SENDER=fail2ban@example.com
      - F2B_ACTION=%(action_)s
      - F2B_IPTABLES_CHAIN=FORWARD # For Docker version 17.06 and higher, use "DOCKER-USER"; otherwise use "FORWARD"
      - SSMTP_HOST=smtp.example.com
      - SSMTP_PORT=587
      - SSMTP_HOSTNAME=example.com
      - SSMTP_USER=smtp@example.com
      - SSMTP_PASSWORD=
      - SSMTP_TLS=YES
    network_mode: host
    privileged: true
    volumes:
      - "${MOUNT_POINT}/docker/fail2ban:/data"
      - "${MOUNT_POINT}/docker/fail2ban/log:/var/log"
      - "${MOUNT_POINT}/docker/shared:/shared"
      - "${MOUNT_POINT}/docker/organizr/www/db:/var/log/organizr:ro" # Organizr login log path
```

I've also tried running fail2ban on the Traefik docker bridge network rather than host but no luck as well. Not sure what's going wrong.
