### ISSUE TITLE
Mail not sent at startup - race condition with msmtpd

### ISSUE THREAD

**Issue by doc75** [crazy-max/docker-fail2ban#181]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/crazy-max/docker-fail2ban/blob/master/.github/SUPPORT.md)

### I've found a bug and checked that ...

- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

When starting fail2ban, the mail indicating that a jail has been started cannot be sent.

### Expected behaviour

I expect the mail to be sent

### Actual behaviour

I can see in the fail2ban log:
```
2025-01-12 16:25:26,522 fail2ban.jail           [1]: INFO    Jail 'error404' started
2025-01-12 16:25:26,528 fail2ban.actions        [1]: ERROR   Failed to start jail 'error404' action 'smtp': Connection unexpectedly closed
```

### Steps to reproduce

use the docker-compose file provided in the example section.
activate at least 1 jail
start fail2ban with docker compose

### Docker info

```text
Client: Docker Engine - Community
 Version:    27.4.1
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.19.3
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.32.1
    Path:     /usr/local/lib/docker/cli-plugins/docker-compose

Server:
 Containers: 30
  Running: 0
  Paused: 0
  Stopped: 30
 Images: 67
 Server Version: 27.4.1
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 88bf19b2105c8b17560993bee28a01ddc2f97182
 runc version: v1.2.2-0-g7cb3632
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 6.1.0-28-amd64
 Operating System: Debian GNU/Linux 12 (bookworm)
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 17.55GiB
 Name: <redacted>
 ID: 57c3b894-b6b4-4198-8a52-6612504f1932
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Username: <redacted>
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

### Docker Compose config

```yaml
name: fail2ban
services:
  fail2ban:
    cap_add:
      - NET_ADMIN
      - NET_RAW
    depends_on:
      msmtpd:
        condition: service_started
        required: true
    environment:
      F2B_DB_PURGE_AGE: 10d
      F2B_LOG_TARGET: /var/log/fail2ban/fail2ban.log
    image: crazymax/fail2ban:latest
    network_mode: host
    restart: unless-stopped
    volumes:
      - type: bind
        source: <redacted>/fail2ban/data
        target: /data
        bind:
          create_host_path: true
      - type: bind
        source: /var/log/docker/fail2ban
        target: /var/log/fail2ban
        bind:
          create_host_path: true
      - type: bind
        source: /var/log/docker/traefik
        target: /var/log/traefik
        read_only: true
        bind:
          create_host_path: true
  msmtpd:
    environment:
      SMTP_AUTH: "on"
      SMTP_FROM: admin@<redacted>
      SMTP_HOST: smtp.<redacted>
      SMTP_PASSWORD: <redacted>
      SMTP_PORT: "587"
      SMTP_STARTTLS: "on"
      SMTP_TLS: "on"
      SMTP_TLS_CHECKCERT: "on"
      SMTP_USER: <redacted>
      TZ: null
    image: crazymax/msmtpd:latest
    networks:
      default: null
    ports:
      - mode: ingress
        host_ip: 127.0.0.1
        target: 2500
        published: "2500"
        protocol: tcp
    restart: unless-stopped
networks:
  default:
    name: fail2ban_default
```

### Logs

```text
N/A
```

### Additional info

I will provide a workaround PR
