### ISSUE TITLE
Expose action.d volume

### ISSUE THREAD

**Issue by onedr0p** [crazy-max/docker-fail2ban#4]
I would love to use a custom action and edit those configuration files but I cannot bind mount `action.d` to my host and see the files.

**Comment by crazy-max** [comment]
@onedr0p Can you post your compose file please ?

**Comment by onedr0p** [comment]
```yaml
version: '2'
services:
  fail2ban:
    image: crazymax/fail2ban:latest
    environment:
      F2B_LOG_LEVEL: DEBUG
      TZ: America/New_York
    stdin_open: true
    volumes:
    - /apps/docker/fail2ban/db:/var/lib/fail2ban
    - /apps/docker/fail2ban/jail.d:/etc/fail2ban/jail.d
    - /var/log:/var/log:ro
    - /apps/docker/fail2ban/filter.d:/etc/fail2ban/filter.d
    - /apps/docker/fail2ban/action.d:/etc/fail2/ban/action.d
```
