### ISSUE TITLE
script error sendmail: Cannot open mail:25

### ISSUE THREAD

**Issue by OKI2020** [crazy-max/docker-fail2ban#48]
F2B tries to send email but fail2ban.utils results in ERROR because it tries to open port 25 
Docker-compose variables set for using smtp mailserver using port 587.

### fail2ban.log : 
2020-06-17 18:09:40,668 fail2ban.utils          [1]: ERROR   7fb382728ab0 -- stderr: 'sendmail: Cannot open mail:25'
2020-06-17 18:09:40,668 fail2ban.utils          [1]: ERROR   7fb382728ab0 -- returned 1
2020-06-17 18:09:40,668 fail2ban.actions        [1]: ERROR   Failed to start jail 'bitwarden' action 'sendmail-whois-lines': Error starting action Jail('bitwarden')/sendmail-whois-lines: 'Script error'
 

### version info
Docker version 18.09.8, build bfed4f5
docker-compose version 1.24.0, build 0aa59064
Linux Zeus 3.10.105 #25426 SMP Tue May 12 04:53:17 CST 2020 x86_64 GNU/Linux synology_broadwell_rs3617rpxs

####Docker-compose
fail2ban:
  image: crazymax/fail2ban:latest
  container_name: fail2ban
  restart: always
  environment: 
    - TZ=Europe/Paris
    - F2B_DB_PURGE_AGE=30d
    - F2B_LOG_TARGET=/data/fail2ban.log
    - F2B_LOG_LEVEL=INFO
    - F2B_IPTABLES_CHAIN=INPUT
    - F2B_DEST_EMAIL=...@...com
    - F2B_SENDER=x@y.com 
    - SSMTP_PORT:587
    - SSMTP_HOST:xxxx
    - SSMTP_HOSTNAME=xxxx
    - SSMTP_USER:xxxx
    - SSMTP_PASSWORD:xxxx
    - SSMTP_TLS=YES
    - SSMTP_STARTTLS:YES

###jail.d

[DEFAULT]
ignoreip = 127.0.0.1/8
#Ban for 30 days
bantime = 2592000
findtime = 86400
maxretry = 3
backend = auto
action = iptables-allports[name=bitwarden]
         sendmail-whois[name=bitwarden, dest=...@....com]

Why does fail2ban still try to open port 25 ?

**Comment by crazy-max** [comment]
@OKI2020 Check your syntax. `- SSMTP_PORT:587` > `- SSMTP_PORT=587`

**Comment by OKI2020** [comment]
changed syntax but still same error

**Comment by crazy-max** [comment]
@OKI2020 What do you have with this compose?:

```yaml
version: "3.5"

services:
  fail2ban:
    image: crazymax/fail2ban:latest
    container_name: fail2ban
    network_mode: "host"
    cap_add:
      - NET_ADMIN
      - NET_RAW
    volumes:
      - "./data:/data"
      - "/var/log:/var/log:ro"
    environment: 
      - "TZ=Europe/Paris"
      - "F2B_DB_PURGE_AGE=30d"
      - "F2B_LOG_TARGET=/data/fail2ban.log"
      - "F2B_LOG_LEVEL=INFO"
      - "F2B_IPTABLES_CHAIN=INPUT"
      - "F2B_DEST_EMAIL=...@...com"
      - "F2B_SENDER=x@y.com"
      - "SSMTP_HOST=xxxx"
      - "SSMTP_PORT=587"
      - "SSMTP_HOSTNAME=xxxx"
      - "SSMTP_USER=xxxx"
      - "SSMTP_PASSWORD:xxxx"
      - "SSMTP_TLS=YES"
      - "SSMTP_STARTTLS=YES"
    restart: always
```
