### ISSUE TITLE
 Unable to ban an ip on a container being connected to a custom bridge network

### ISSUE THREAD

**Issue by jordan38** [crazy-max/docker-fail2ban#49]
### Behaviour

>I want to ban ip after multi retry false login on the container owncloud

#### Steps to reproduce this issue

1. Log in multiple times with bad credentials on owncloud

#### Expected behaviour

>The IP that made several errors on the owncloud login must be banned

### Configuration

* Docker version (type `docker --version`) : 
> Docker version 19.03.5, build 633a0ea
* Docker compose version if applicable (type `docker-compose --version`) : 
> docker-compose version 1.25.1, build a82fef0
* Platform (Debian 9, Ubuntu 18.04, ...) : 

>Distributor ID: Raspbian
  Description:    Raspbian GNU/Linux 10 (buster)
  Release:        10
  Codename:       buster

* System info (type `uname -a`) :  
> Linux stark 4.19.75-v7l+ #1270 SMP Tue Sep 24 18:51:41 BST 2019 armv7l GNU/Linux

* Include all necessary configuration files : `docker-compose.yml`, `.env`, ...

> filder.d -> owncloud.conf

```[Definition]
failregex={.*Login failed: \'.*\' \(Remote IP: \'<HOST>\'\)"}
ignoreregex =
```
> jail.d -> owncloud.conf
```
[owncloud]
enabled = true
port = http, https
protocol = tcp
filter = owncloud
maxretry = 3
bantime = 4w
logpath = /var/log/owncloud.log
```
> docker-compose-owncloud.yml

```
  sync_cloud:
    image: owncloud/server:${SYNC_TAG}
    container_name: sync_cloud
    environment:
      - OWNCLOUD_DOMAIN=${SYNC_SERVER_HOSTNAME}
      # DATABASE
      - OWNCLOUD_DB_HOST=sync_db
      - OWNCLOUD_DB_TYPE=mysql
      - OWNCLOUD_DB_NAME=${SYNC_DB_NAME}
      - OWNCLOUD_DB_USERNAME=${SYNC_DB_USER}
      - OWNCLOUD_DB_PASSWORD=${SYNC_DB_PASS}
      # OWNCLOUD Administration
      - OWNCLOUD_ADMIN_USERNAME=${SYNC_ADMIN_USER}
      - OWNCLOUD_ADMIN_PASSWORD=${SYNC_ADMIN_PASS}
      # OWNCLOUD Cache
      - OWNCLOUD_REDIS_HOST=sync_cache
      - OWNCLOUD_REDIS_ENABLED=true
      # OWNCLOUD Log
      - OWNCLOUD_LOG_LEVEL=2
    volumes:
      - ${SYNC_SYNC_FOLDER}:/mnt/data
      - ${SYNC_LOG}:/mnt/data/files/owncloud.log
    labels:
      # SYNC HTTP
      - "traefik.enable=true"
      - "traefik.http.routers.sync.rule=Host(`${SYNC_SERVER_HOSTNAME}`)"
      - "traefik.http.routers.sync.entrypoints=http"
      - "traefik.http.services.sync.loadbalancer.server.port=8080"
      - "traefik.http.routers.sync.middlewares=redirect-to-https"
      # SYNC HTTPS
      - "traefik.http.routers.sync-https.rule=Host(`${SYNC_SERVER_HOSTNAME}`)"
      - "traefik.http.routers.sync-https.entrypoints=https"
      - "traefik.http.routers.sync-https.tls=true"
      - "traefik.http.routers.sync-https.tls.certresolver=eastwatch"
    networks:
      - web
```

> docker-network web
```
docker_network:
        name: web
        driver: bridge
        ipam_config:
          - subnet: 172.19.0.0/16
            gateway: 172.19.0.1
        driver_options:
          com.docker.network.bridge.default_bridge: false
          com.docker.network.bridge.enable_icc: true
          com.docker.network.bridge.enable_ip_masquerade: true
          com.docker.network.bridge.host_binding_ipv4: 0.0.0.0
          com.docker.network.bridge.name: docker1
          com.docker.network.bridge.mtu: 1500
```

> docker-compose-traefik.yml
```
reverse-proxy:
    image: traefik:${REVERSE_PROXY_TAG}
    container_name: reverse-proxy
    ports:
      - 443:443
      - 80:80
      - 8080:8080
    environment:
      - TZ=${TIMEZONE}
    volumes:
      - ${REVERSE_PROXY_STATIC_CONFIG}:/etc/traefik/traefik.toml
      - ${REVERSE_PROXY_DYNAMIC_CONFIG}:/etc/traefik/services.toml
      - ${REVERSE_PROXY_LETSENCRYPT_FOLDER}:/letsencrypt
      - ${DOCKER_VOLUME_SOCK}:/var/run/docker.sock:ro
      - ${REVERSE_PROXY_LOG}:/var/log
    labels:
      # DASHBOARD
      - "traefik.http.routers.api.rule=Host(`${API_TRAEFIK_HOSTNAME}`)"
      - "traefik.http.routers.api.service=api@internal"
      - "traefik.http.routers.api.entrypoints=http"
      - "traefik.http.routers.api.middlewares=auth"
      - "traefik.http.middlewares.auth.basicauth.users=${REVERSE_PROXY_DASHBOARD_USER}:${REVERSE_PROXY_DASHBOARD_PASS}"
      # MIDDLEWARES
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
      # KINGSLANDING HTTP
      - "traefik.http.routers.kingslanding.rule=Host(`${KINGSLANDING_HOSTNAME}`)"
      - "traefik.http.routers.kingslanding.service=kingslanding@file"
      - "traefik.http.routers.kingslanding.entrypoints=http"
      # NETGEAR HTTP
      - "traefik.http.routers.netgear.rule=Host(`${NETGEAR_ROUTEUR_HOSTNAME}`)"
      - "traefik.http.routers.netgear.service=netgear@file"
      - "traefik.http.routers.netgear.entrypoints=http"
      # LIVEBOX HTTP
      - "traefik.http.routers.livebox.rule=Host(`${LIVEBOX_ROUTEUR_HOSTNAME}`)"
      - "traefik.http.routers.livebox.service=livebox@file"
      - "traefik.http.routers.livebox.entrypoints=http"
      # BITTORENT HTTP
      - "traefik.http.routers.bittorent.rule=Host(`${BITTORENT_HOSTNAME}`)"
      - "traefik.http.routers.bittorent.service=bittorent@file"
      - "traefik.http.routers.bittorent.entrypoints=http"
      # MEDIA LIBRARY HTTP
      - "traefik.http.routers.media-library.rule=Host(`${MEDIA_LIBRARY_HOSTNAME}`)"
      - "traefik.http.routers.media-library.service=media-library@file"
      - "traefik.http.routers.media-library.entrypoints=http"
      # DNS-SERVER HTTP
      - "traefik.http.routers.dns-server.rule=Host(`${DNS_SERVER_HOSTNAME}`)"
      - "traefik.http.routers.dns-server.service=dns-server@file"
      - "traefik.http.routers.dns-server.entrypoints=http"
    networks:
        - web
```

> docker-compose-fail2ban.yml
```
fail2ban-docker:
        image: crazymax/fail2ban:${FAIL2BAN_TAG}
        container_name: fail2ban-docker
        environment:
            - F2B_LOG_TARGET=STDOUT
            - F2B_LOG_LEVEL=DEBUG
            - F2B_DB_PURGE_AGE=1d
            - TZ=${TIMEZONE}
            - F2B_IPTABLES_CHAIN=DOCKER-USER
        volumes:
            - ${FAIL2BAN_DOCKER_FOLDER_DATA_FILTER}:/data/filter.d
            - ${FAIL2BAN_DOCKER_FOLDER_DATA_JAIL}:/data/jail.d
            # - ${FAIL2BAN_DATA_DB}:/data/db
            - ${FAIL2BAN_FOLDER_SCRAP_LOG}:/var/log:ro
        cap_add:
            - NET_ADMIN
            - NET_RAW
        network_mode: host
        restart: always
```

### Docker info

```
> Client:
 Debug Mode: false

Server:
 Containers: 8
  Running: 8
  Paused: 0
  Stopped: 0
 Images: 7
 Server Version: 19.03.5
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: b34a5c8af56e510852c35414db4c1f4fa6172339
 runc version: 3e425f80a8c931f88e6d94a8c831b9d5aa481657
 init version: fec3683
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 4.19.75-v7l+
 Operating System: Raspbian GNU/Linux 10 (buster)
 OSType: linux
 Architecture: armv7l
 CPUs: 4
 Total Memory: 3.863GiB
 Name: stark
 ID: HJOH:HX4T:DJYE:GDHO:NWXL:SFQN:57ST:KI56:ICFU:ZTWL:3UUH:RBEE
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No swap limit support
WARNING: No cpu cfs quota support
WARNING: No cpu cfs period support`
```

### Logs

```
2020-06-20 15:13:01,586 fail2ban.observer       [1]: DEBUG   [owncloud] Observer: ban found 80.214.214.116, 2419200
2020-06-20 15:13:01,618 fail2ban.utils          [1]: ERROR   b6597bd0 -- exec: iptables -w -N f2b-owncloud iptables -w -A f2b-owncloud -j RETURN iptables -w -I DOCKER-USER -p tcp -m multiport --dports http, https -j f2b-owncloud
2020-06-20 15:13:01,618 fail2ban.utils          [1]: ERROR   b6597bd0 -- stderr: 'iptables: Chain already exists.'
2020-06-20 15:13:01,619 fail2ban.utils          [1]: ERROR   b6597bd0 -- stderr: "iptables v1.8.3 (legacy): invalid port/service `' specified"
2020-06-20 15:13:01,619 fail2ban.utils          [1]: ERROR   b6597bd0 -- stderr: "Try `iptables -h' or 'iptables --help' for more information."
2020-06-20 15:13:01,619 fail2ban.utils          [1]: ERROR   b6597bd0 -- returned 2
2020-06-20 15:13:01,620 fail2ban.actions        [1]: ERROR   Failed to execute ban jail 'owncloud' action 'iptables-multiport' info 'ActionInfo({'ip': '80.214.214.116', 'family': 'inet4', 'fid': <function Actions.ActionInfo.<lambda> at 0xb65bb220>, 'raw-ticket': <function Actions.ActionInfo.<lambda> at 0xb65bb580>})': Error starting action Jail('owncloud')/iptables-multiport: 'Script error'


Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/fail2ban/server/actions.py", line 482, in __checkBan action.ban(aInfo)
  File "/usr/lib/python3.8/site-packages/fail2ban/server/action.py", line 548, in ban
    self._start(family, forceStart=True)
  File "/usr/lib/python3.8/site-packages/fail2ban/server/action.py", line 529, in _start
    ret = self._executeOperation('<actionstart>', 'starting', family=family, afterExec=_started)
  File "/usr/lib/python3.8/site-packages/fail2ban/server/action.py", line 462, in _executeOperation
    raise RuntimeError("Error %s action %s/%s: %r" % (operation, self._jail, self._name, err))

RuntimeError: Error starting action Jail('owncloud')/iptables-multiport: 'Script error'
```
