### ISSUE TITLE
Rootless Docker: stderr: 'iptables: No chain/target/match by that name.'

### ISSUE THREAD

**Issue by schklom** [crazy-max/docker-fail2ban#86]
#### Steps to reproduce this issue

1. Use Rootless Docker
2. Try to get banned
3. Error

#### Expected behaviour

> Tell me what should happen
Ban should work
#### Actual behaviour

> Tell me what happens instead
iptables error

### Configuration

* Docker version (type `docker --version`) : `Docker version 20.10.3, build 48d30b5`
* Docker compose version if applicable (type `docker-compose --version`) :  `docker-compose version 1.28.4, build unknown`
* Platform (Debian 9, Ubuntu 18.04, ...) : Debian 10
* System info (type `uname -a`) : Linux <hostname> 5.9.0-0.bpo.5-arm64 #1 SMP Debian 5.9.15-1~bpo10+1 (2020-12-31) aarch64 GNU/Linux
* Include all necessary configuration files : `docker-compose.yml`, `.env`, ...
```
  fail2ban:
    image: crazymax/fail2ban
    container_name: fail2ban
    cap_add:
      - NET_ADMIN
      - NET_RAW
    volumes:
      - ${DOCKERCONFIG}/fail2ban:/data
      - /var/log/docker:/var/log/docker
    environment:
      - TZ=${TZ}
      - F2B_LOG_TARGET=STDOUT
      - F2B_LOG_LEVEL=INFO
      - F2B_DB_PURGE_AGE=7d
```
### Docker info

```
Client:
 Context:    default
 Debug Mode: false

Server:
 Containers: 11
  Running: 11
  Paused: 0
  Stopped: 0
 Images: 24
 Server Version: 20.10.3
 Storage Driver: fuse-overlayfs
 Logging Driver: json-file
 Cgroup Driver: none
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc version: ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
  rootless
 Kernel Version: 5.9.0-0.bpo.5-arm64
 Operating System: Debian GNU/Linux 10 (buster)
 OSType: linux
 Architecture: aarch64
 CPUs: 4
 Total Memory: 7.631GiB
 Name: <hostname>
 ID: JEXP:SIXA:6AG6:CMB3:C6XY:MCMO:YITL:WT7V:NYBP:3PIB:3LPR:IDF6
 Docker Root Dir: /home/schklom/.local/share/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
 Product License: Community Engine
 Default Address Pools:
   Base: 192.168.0.0/16, Size: 24

WARNING: Running in rootless-mode without cgroups. To enable cgroups in rootless-mode, you need to boot the system in cgroup v2 mode.
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
```

### Logs

```
fail2ban.actions        [1]: NOTICE  [<service_name>] Ban XX.XX.XX.XX
fail2ban.utils          [1]: ERROR   ffff9bbbdea0 -- exec: iptables -w -N f2b-<service_name>
iptables -w -A f2b-<service_name> -j RETURN
iptables -w -I DOCKER-USER -p tcp -j f2b-<service_name>
```
